pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2 -v /var/run/docker.sock:/var/run/docker.sock --privileged'
        }
    }
    stages {
        stage('Info') {
            steps {
                step {
                    sh echo 'PIPELINE STARTED YO'
                }
            }
        }
        stage('Build') {
            steps {
                sh dockerd
                sh 'mvn -B -DskipTests clean package'
            }
        }
    }
}