pipeline {

    agent {
        docker {
            image 'maven:3.5.2-jdk-8'
            args '-v /root/.m2:/root/.m2 -v /var/run/docker.sock:/var/run/docker.sock --privileged'
        }
    }

    stages {

        stage('Info') {
            steps {
                echo 'Pipeline started'
            }
        }

        stage('Build') {
            steps {
                echo 'Build running'
                sh 'mvn -e -B -DskipTests clean package -Dproject.upload.directory=./target'
                sh 'RELEASE_VERSION = mvn -q -Dexec.executable="echo" -Dexec.args=\'${project.version}\' --non-recursive exec:exec'
            }
        }

    }

    post {
        success {
            echo "Everything finished successfully"
        }
        failure {
            echo " Build failed miserably"
        }
    }

}