pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2 -v /var/run/docker.sock:/var/run/docker.sock --privileged'
        }
    }
    stages {

        stage('Info') {
            steps {
                echo 'PIPELINE STARTED YO'
            }
        }

        stage('Build') {
            steps {
                echo 'BUILD IS RUNNING YO'
                sh dockerd -v
                sh 'mvn -B -DskipTests clean package'
            }
        }

    }
}